### ISSUE TITLE
Can't find codes about "Face recognition task" and  "Contrastive self-supervised learning task",can you provide them?

### ISSUE THREAD

**Issue by cqfei** [Dyfine/SphericalEmbedding#3]

**Comment by Dyfine** [comment]
Hi~ We did not plan to provide these codes, you can refer to the repos below and easily add SEC based on them:
face recognition: https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch
contrastive learning: https://github.com/Dyfine/SimCLR_pytorch_distributed

**Comment by cqfei** [comment]
Got it, thanks
